cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'homebrew/cask-fonts'

# core apps
brew 'coreutils'
brew 'bat'
brew 'fasd'
brew 'fd'
brew 'fzf'
brew 'git'
brew 'htop'
brew 'python3'
brew 'ripgrep'
brew 'tmux'

#brew 'stow'
#brew 'zsh'

# tools
#brew 'bash'
#brew 'bash-completion'
brew 'tree'
brew 'wget'
#brew 'youtube-dl'
#brew 'z'

# development
#brew 'boost'
#brew 'cscope'
#brew 'gdb'
#brew 'go'
#brew 'libgit2'
#brew 'qt'
#brew 'rust'
#brew 'macvim'
#brew 'renameutils'
#brew 'node'
#brew 'openssl'
#brew 'thrift'

# casks
#cask 'iterm2'
cask 'font-hack-nerd-font'
#cask '1password'
#cask 'dropbox'
#cask 'google-chrome'
#cask 'meld'
#cask 'the-unarchiver'
#cask 'vlc'
