cask_args appdir: '/Applications'

tap 'homebrew/bundle'

# core apps
brew 'git'
brew 'zsh'
brew 'fasd'
brew 'fd'
brew 'fzf'
brew 'ripgrep'
brew 'stow'
brew 'vim --with-python3'

# tools
#brew 'bash'
#brew 'bash-completion'
#brew 'tree'
#brew 'wget'
#brew 'youtube-dl'
#brew 'z'

# development
#brew 'coreutils'
#brew 'renameutils'
#brew 'boost'
#brew 'gdb'
#brew 'go'
#brew 'thrift'
#brew 'node'
#brew 'openssl'
#brew 'python'
#brew 'libgit2'

# casks
cask 'iterm2'
#cask '1password'
#cask 'dropbox'
#cask 'google-chrome'
#cask 'meld'
#cask 'the-unarchiver'
#cask 'vlc'
